name: kantin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.1
  crop_your_image: 2.0.0
  cropperx: ^1.1.1
  firebase_app_check: ^0.3.2+1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_credit_card: ^4.0.1
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  image_picker: ^1.1.2
  intl: ^0.20.1
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  image_cropper: ^9.0.0
  dotted_border: ^2.1.0
  image: ^4.0.17
  flutter_dotenv: ^5.0.2
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  avatar_glow: ^2.0.1
  path_provider: ^2.1.1
  slideable: ^0.0.2
  flutter_slidable: ^0.6.0
  glassmorphism: ^3.0.0
  carousel_slider: ^5.0.0
  qr_flutter: ^4.1.0
  photo_view: ^0.14.0
  reorderables: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - .env
